default_language_version:
  python: python3

exclude: |
  (?x)^(
    .*thirdparty/.*|
    .*-so_wrap\.(h|c)$
  )

repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.0
    hooks:
      - id: clang-format
        files: \.(c|h|cpp|hpp|cc|hh|cxx|hxx|m|mm|inc|java|glsl)$
        types_or: [text]
        exclude: |
          (?x)^(
            lib/.*|
            tests/.*
          )

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-tidy
        files: \.(c|h|cpp|hpp|cc|hh|cxx|hxx|m|mm|inc|java|glsl)$
        args: [--fix, --quiet, --use-color]
        types_or: [text]
        exclude: |
          (?x)^(
            tests/python_build/.*|
            platform/android/java/editor/src/main/java/com/android/.*|
            platform/android/java/lib/src/com/.*
          )
        additional_dependencies: [clang-tidy==18.1.1]
        require_serial: true
        stages: [manual] # Not automatically triggered, invoked via `pre-commit run --hook-stage manual clang-tidy`

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        files: \.py$
        types_or: [text]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        exclude: |
          (?x)^(
            platform/android/java/editor/src/main/java/com/android/.*|
            platform/android/java/lib/src/com/.*
          )
        additional_dependencies: [tomli]

